import { describe, expect, it } from 'vitest';
import { hasValidCheckDigit, looksLikeFunkoUpc, normaliseUpc } from '@/lib/upc';

/**
 * The real Funko barcodes below are taken from published barcode databases, so
 * these tests check the algorithm against ground truth rather than against
 * numbers generated by the same code that validates them.
 */
const REAL_FUNKO_UPCS = [
  '889698117081', // Pop! Star Wars Rey #161
  '889698563079', // Pop! Games Pokemon Pikachu
  '889698338769', // Pop! Animation Simpsons Bartman
];

describe('hasValidCheckDigit', () => {
  it('accepts real Funko barcodes', () => {
    for (const upc of REAL_FUNKO_UPCS) {
      expect(hasValidCheckDigit(upc)).toBe(true);
    }
  });

  it('accepts a real non-Funko UPC too — it is not a brand check', () => {
    expect(hasValidCheckDigit('045496830434')).toBe(true);
  });

  it('rejects a single mistyped digit', () => {
    // 889698117081 with the 7 turned into an 8.
    expect(hasValidCheckDigit('889698118081')).toBe(false);
  });

  it('rejects two adjacent digits transposed', () => {
    expect(hasValidCheckDigit('889698171081')).toBe(false);
  });

  it('rejects lengths the algorithm is not defined for', () => {
    expect(hasValidCheckDigit('88969811708')).toBe(false);
    expect(hasValidCheckDigit('8896981170812')).toBe(false);
  });
});

describe('normaliseUpc', () => {
  it('strips the punctuation people type off a box', () => {
    const result = normaliseUpc(' 8 89698-117081 ');
    expect(result).toEqual({ ok: true, upc: '889698117081', padded: false });
  });

  it('rejects a mistyped digit with an actionable message', () => {
    const result = normaliseUpc('889698118081');
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.error).toMatch(/check digit/i);
  });

  /*
   * The spreadsheet hazard. A UPC with a leading zero loses it when a CSV
   * column is parsed as a number, and the shortened value is still
   * checksum-valid — so this padding is the only thing standing between a
   * round-trip through Excel and a silently wrong identifier.
   */
  it('restores a leading zero eaten by a spreadsheet', () => {
    const result = normaliseUpc('45496830434');
    expect(result).toEqual({ ok: true, upc: '045496830434', padded: true });
  });

  it('demonstrates why padding is needed rather than relying on the checksum', () => {
    // Both pass the checksum; only length tells them apart.
    expect(hasValidCheckDigit('045496830434')).toBe(true);
    expect(hasValidCheckDigit('45496830434'.padStart(12, '0'))).toBe(true);
  });

  it('rejects scientific notation instead of storing a mangled number', () => {
    const result = normaliseUpc('8.89698E+11');
    expect(result.ok).toBe(false);
    if (result.ok) throw new Error('unreachable');
    expect(result.error).toMatch(/digits only/i);
  });

  it('rejects things that are obviously not a UPC', () => {
    expect(normaliseUpc('12345').ok).toBe(false);
    expect(normaliseUpc('').ok).toBe(false);
    expect(normaliseUpc('889698117081999').ok).toBe(false);
  });

  it('accepts a 13-digit EAN unchanged', () => {
    // A valid EAN-13.
    expect(normaliseUpc('4006381333931')).toEqual({
      ok: true,
      upc: '4006381333931',
      padded: false,
    });
  });
});

/**
 * Real early-line barcodes, read off PriceCharting's catalogue entries. The
 * 2011 Pops predate the 889698 prefix entirely.
 */
const EARLY_FUNKO_UPCS = [
  '830395023908', // Darth Maul #9, January 2011
  '849803068271', // Darth Vader #1, January 2011
  '849803055400', // Yoda #2, May 2011
];

describe('early-line barcodes', () => {
  it('validates by checksum like any other', () => {
    for (const upc of EARLY_FUNKO_UPCS) {
      expect(hasValidCheckDigit(upc)).toBe(true);
      expect(normaliseUpc(upc).ok).toBe(true);
    }
  });
});

describe('looksLikeFunkoUpc', () => {
  it('recognises the prefix Funko actually uses', () => {
    for (const upc of REAL_FUNKO_UPCS) {
      expect(looksLikeFunkoUpc(upc)).toBe(true);
    }
  });

  /*
   * Flagging every 2011 figure as suspicious is how a warning gets ignored.
   */
  it('does not cry wolf on the pre-2017 prefixes', () => {
    for (const upc of EARLY_FUNKO_UPCS) {
      expect(looksLikeFunkoUpc(upc)).toBe(true);
    }
  });

  it('does not claim a video game barcode is a Funko', () => {
    expect(looksLikeFunkoUpc('045496830434')).toBe(false);
  });
});
